First iteration
e0ipso/shaper pull request #10
Opened 2018-07-23 08:02 UTC by ndobromirov

- Unified errors code generation.
- Using late static binding for the classes shown in the message, so we see actual adapter and not the strange base class.

2018-07-23 10:53 UTC, e0ipso requested changes
This looks great! I like the feature. Only some minor comments about coding standards.

Also, let's make sure code coverage remains at 100%.

2018-07-23 10:53 UTC, e0ipso commented on .gitignore
> +.idea
Let's remove this. Please use `echo .idea >> .git/info/exclude` instead.

2018-07-23 10:53 UTC, e0ipso commented on src/Transformation/TransformationTransformerTrait.php
> +    $throwError = function($message, $arguments = []) {
Let's use snake case for all variable names. We will be observing Drupal Coding Standards in this library.

2018-07-23 10:53 UTC, e0ipso commented on src/Transformation/TransformationTransformerTrait.php
> +      $throwError('Adaptor {class} received invalid input data: {data}.');
♨️ nice!

2018-07-25 13:14 UTC, e0ipso commented
@ndobromirov thanks again for the fixes. The only remaining issue blocking this commit is the code coverage. We should not merge PRs that decrease code coverage.

2018-07-26 09:55 UTC, ndobromirov commented
The average test coverage decreased, as the lines that had test coverage are less and the ones without are the same. The file being changed is still 100% covered see the [coveralls reoprt](https://coveralls.io/builds/18152895/source?filename=src%2FTransformation%2FTransformationTransformerTrait.php).

I can add missing coverage for the 2 other files, but changing code there is unrelated to the issue at hand.

2018-07-26 09:59 UTC, e0ipso commented
I see what you mean.

> I can add missing coverage for the 2 other files, but changing code there is unrelated to the issue at hand.

That'd be awesome! I'll create a ticket for that. I won't block this work any further. Thanks for your patience.

2018-07-26 09:59 UTC, e0ipso approved these changes

2018-07-26 10:00 UTC, merged

2018-07-26 10:03 UTC, e0ipso commented
Issue created: https://github.com/e0ipso/shaper/issues/11